### PR TITLE
fix build warning when compiling the app

### PR DESCRIPTION
**Pull request by Adzz**
should fix this:

screen shot 2018-06-07 at 13 58 01

### CODE REVIEW

**Comment by AndrewDryga** [comment]
Hello, @Adzz! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/Nebo15/confex/pulls/30). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by AndrewDryga** [comment]
Hey @Adzz. The test won't work after your fix because we are using doctests and they are sensitive for additional spaces. I'm pretty sure there is magical fix for this (like using some sigil for doc comment), but not sure which one to use. If you can find a way to fix this - it would be awesome :).

**Comment by Adzz** [comment]
Ah good point!

@AndrewDryga  I can see two simple solutions, which do you prefer?

1. Don't split the output over two lines
2. something like this:
```elixir
@error_message """
  can not resolve key MY_TEST_ENV value via adapter Elixir.Confex.Adapters.SystemEnvironment
"""
# ... more code
"""
      iex> :ok = System.delete_env("MY_TEST_ENV")
      ...> Application.put_env(:myapp, :test_var, {:system, :integer, "MY_TEST_ENV"})
      ...> #{__MODULE__}.fetch_env!(:myapp, :test_var)
      ** (ArgumentError) can't fetch value for key `:test_var` of application `:myapp`, #{@error_message}
"""
```

The other option is to sack of doctests, and use normal tests, but I imagine that's a no!

Sigils wont work. `~S"""` means the string wont let you use escape codes, which means we can't escape a new line, which means we have to have one long line anyway.

**Comment by AndrewDryga** [comment]
Let's leave it in on long line then

**Pull request merged**
